package android.db.boxme.model;

/**
 * Created by Caritor on 12/16/2016.
 */
public class GitForkee {

    public long id;// 75391308,
    public String name;// "Cryptography",
    public String full_name;// "dineshbalu/Cryptography",
    public User owner;
//        "private": false,
    public String html_url;// "https://github.com/dineshbalu/Cryptography",
    public String description;// "Encryption-Decryption in Android",
    public String fork;// true,
    public String url;// "https://api.github.com/repos/dineshbalu/Cryptography",
    public String forks_url;// "https://api.github.com/repos/dineshbalu/Cryptography/forks",
    public String keys_url;// "https://api.github.com/repos/dineshbalu/Cryptography/keys{/key_id}",
    public String collaborators_url;// "https://api.github.com/repos/dineshbalu/Cryptography/collaborators{/collaborator}",
    public String teams_url;// "https://api.github.com/repos/dineshbalu/Cryptography/teams",
    public String hooks_url;// "https://api.github.com/repos/dineshbalu/Cryptography/hooks",
    public String issue_events_url;// "https://api.github.com/repos/dineshbalu/Cryptography/issues/events{/number}",
    public String events_url;// "https://api.github.com/repos/dineshbalu/Cryptography/events",
    public String assignees_url;// "https://api.github.com/repos/dineshbalu/Cryptography/assignees{/user}",
    public String branches_url;// "https://api.github.com/repos/dineshbalu/Cryptography/branches{/branch}",
    public String tags_url;// "https://api.github.com/repos/dineshbalu/Cryptography/tags",
    public String blobs_url;// "https://api.github.com/repos/dineshbalu/Cryptography/git/blobs{/sha}",
    public String git_tags_url;// "https://api.github.com/repos/dineshbalu/Cryptography/git/tags{/sha}",
    public String git_refs_url;// "https://api.github.com/repos/dineshbalu/Cryptography/git/refs{/sha}",
    public String trees_url;// "https://api.github.com/repos/dineshbalu/Cryptography/git/trees{/sha}",
    public String statuses_url;// "https://api.github.com/repos/dineshbalu/Cryptography/statuses/{sha}",
    public String languages_url;// "https://api.github.com/repos/dineshbalu/Cryptography/languages",
    public String stargazers_url;// "https://api.github.com/repos/dineshbalu/Cryptography/stargazers",
    public String contributors_url;// "https://api.github.com/repos/dineshbalu/Cryptography/contributors",
    public String subscribers_url;// "https://api.github.com/repos/dineshbalu/Cryptography/subscribers",
    public String subscription_url;// "https://api.github.com/repos/dineshbalu/Cryptography/subscription",
    public String commits_url;// "https://api.github.com/repos/dineshbalu/Cryptography/commits{/sha}",
    public String git_commits_url;// "https://api.github.com/repos/dineshbalu/Cryptography/git/commits{/sha}",
    public String comments_url;// "https://api.github.com/repos/dineshbalu/Cryptography/comments{/number}",
    public String issue_comment_url;// "https://api.github.com/repos/dineshbalu/Cryptography/issues/comments{/number}",
    public String contents_url;// "https://api.github.com/repos/dineshbalu/Cryptography/contents/{+path}",
    public String compare_url;// "https://api.github.com/repos/dineshbalu/Cryptography/compare/{base}...{head}",
    public String merges_url;// "https://api.github.com/repos/dineshbalu/Cryptography/merges",
    public String archive_url;// "https://api.github.com/repos/dineshbalu/Cryptography/{archive_format}{/ref}",
    public String downloads_url;// "https://api.github.com/repos/dineshbalu/Cryptography/downloads",
    public String issues_url;// "https://api.github.com/repos/dineshbalu/Cryptography/issues{/number}",
    public String pulls_url;// "https://api.github.com/repos/dineshbalu/Cryptography/pulls{/number}",
    public String milestones_url;// "https://api.github.com/repos/dineshbalu/Cryptography/milestones{/number}",
    public String notifications_url;// "https://api.github.com/repos/dineshbalu/Cryptography/notifications{?since,all,participating}",
    public String labels_url;// "https://api.github.com/repos/dineshbalu/Cryptography/labels{/name}",
    public String releases_url;// "https://api.github.com/repos/dineshbalu/Cryptography/releases{/id}",
    public String deployments_url;// "https://api.github.com/repos/dineshbalu/Cryptography/deployments",
    public String created_at;// "2016-12-02T11:50:08Z",
    public String updated_at;// "2015-08-25T04:46:37Z",
    public String pushed_at;// "2014-12-18T12:21:04Z",
    public String git_url;// "git://github.com/dineshbalu/Cryptography.git",
    public String ssh_url;// "git@github.com:dineshbalu/Cryptography.git",
    public String clone_url;// "https://github.com/dineshbalu/Cryptography.git",
    public String svn_url;// "https://github.com/dineshbalu/Cryptography",
    public String homepage;// null,
    public String size;// 1072,
    public String stargazers_count;// 0,
    public String watchers_count;// 0,
    public String language;// null,
    public String has_issues;// false,
    public String has_downloads;// true,
    public String has_wiki;// true,
    public String has_pages;// false,
    public String forks_count;// 0,
    public String mirror_url;// null,
    public String open_issues_count;// 0,
    public String forks;// 0,
    public String open_issues;// 0,
    public String watchers;// 0,
    public String default_branch;// "master",
//    public String public": true

}
